#!/bin/bash

if [ "$#" -ne 2 ]
then
	echo 'Usage: cuesplit CUEFILE DATAFILE'
	exit
fi

# split cue sheet into flac tracks
mkdir flac
shnsplit -f "$1" -d flac -t %n\ -\ %t -o flac "$2"

# tag the tracks
cuetag "$1" flac/*.flac

# reencode in opus
mkdir opus
cd flac
for x in *.flac
do
	ffmpeg -i "$x" -c:a libopus -vbr on -compression_level 10 -b:a 128000 "../opus/${x%.*}.opus"
done
cd ..

# clean up flac tracks
rm -r flac
