#!/bin/bash

if [ "$#" -ne 2 ]
then
	echo 'Usage: cuesplit CUEFILE DATAFILE'
	exit
fi

# split cue sheet into wave tracks
mkdir wav
shnsplit -f "$1" -d wav -t %n\ -\ %t -o wav "$2"

# tag the tracks
cuetag "$1" wav/*.wav

# reencode in opus
mkdir opus
cd wav
for x in *.wav
do
	ffmpeg -i "$x" -c:a libopus -vbr on -compression_level 10 -b:a 128000 "../opus/${x%.*}.opus"
done
cd ..

# clean up wave tracks
rm -r wav
