#!/bin/bash
# enable globstar for recursive file search
shopt -s globstar

# execute actual reencoding operations
for x in ./**/*.flac; do
	ffmpeg -i "$x" -c:a libopus -vbr on -compression_level 10 -b:a 128000 "${x%.flac}.ogg"
done

# setup start of body of mail notification
if [ -f mailbody ]; then rm mailbody; fi
echo 'Reencoding ${PWD##*/} in Opus: done.' >> mailbody

# look, starting from scratch, that each flac file has an ogg equivalent
errors=( )
for f in ./**/*.flac; do
	if [ -f "${f%.flac}.ogg" ]; then
		# the ogg exists, we silently remove the flac
                rm "$f"
        else
		# the ogg doesn't exist, we log this
		errors=( "${errors[@]}" "$f" )
        fi
done

# complete body of email notification
if [ ${#errors[@]} = 0 ]; then
	echo 'Operation completed successfully.' >> mailbody
else	
	echo 'Some files were not converted to Opus:'
	printf '%s\n' "${errors[@]}" >> mailbody
fi

# send email notification
cat mailbody | mail -s 'Reencoding ${PWD##*/}' fabrizio07@gmail.com

# cleanup
rm mailbody
